### ISSUE TITLE
training failed when only predicting source tags

### ISSUE THREAD

**Issue by iamhere1** [Unbabel/OpenKiwi#91]
When I run the experiment with training bert based qe models and predicting only the source tags, it failed after reporting for the metric on validation dataset. The error occured as below. It seems the function "self.monitor_op(current - self.min_delta, self.best)" could only run on cpu. But when I run the training process and predicting all the source tags, target tags and the other tags, the training process is ok. 

![image](https://user-images.githubusercontent.com/8308024/99789900-476a4880-2b5e-11eb-8cd3-cfcc760dfa53.png)

**Comment by daandouwe** [comment]
This is interesting, thank you. I believe we have never trained on just source tags, so that must be why we have never encountered this error before. Thank you for reporting it. 

Let me just setup a little experiment to try and reproduce this, and will report to you when I understand how this could be fixed.

**Comment by daandouwe** [comment]
I just tried to train Bert and XLM-R based models on GPU with predicting just source tags, and did not encounter this problem. I used

```yaml
trainer:
    main_metric:
        - source_tags_MCC
```
and 
```yaml
system:
    model:
        outputs:
            word_level:
                target: false
                gaps: false
                source: true
```

Could you share (the relevant parts of) your config? For example, what is `main_metric` that you are using?
